---
title: "regen and plot analysis"
author: "Peter Smallidge"
date: "5/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Initialize Libraries
```{r, include=FALSE}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
library(readxl)
library(readr)
#
# ALT plus hypen = <- (within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# ALT + - = insert assignment operator
# filter rows, select columns
# RMD comment = <!-- comment -->
# 
# 

```


### read data from csv file, check variables and data structure

```{r, data input}

plot_tidy <- read_csv("tidy_plot_2019.csv") %>% 
  mutate_at(vars(harvest, year, point, location, plot_attrib, attrib_val),
            list(factor))

plot_untidy <- read_csv("untidy_plot_2019.csv") %>% 
  mutate_at(vars(harvest, year, point, location, 
                 disturb, slash, fern, herb, 
                 low_cov, inv_cov, mid_cov, upper_cov, vine_cov,
                  comm_stock, pre_comm_stock, diver_stock,
                  pre_diver_stock,  interf_woody_stock, fern_stock, all_intf,
                 winner_stock),
            list(factor)) %>% 
  replace_na(list("comm_stock" = "no"))
  



#need to check the variables "_stock" some missing or miss-named
#note that type = diverse includes commercial and diversity spp
#

regen_tidy <- read_csv("tidy_regen_point_2019.csv")   %>% 
  mutate_at(vars(harvest, location, point, spp, origin, year, type, size),
             list(factor))
  
  


```
```{r}
# the table function (base R) provides the count of occurrences of two 
# categorical (factor) variables. In the first example the number of 
# plots that had commercial stocking (no vs. stocked) among each level
# of ratings of low % cover (absent, present, low, medium, high)

table(plot_untidy$comm_stock, plot_untidy$low_cov,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$mid_cov,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$upper_cov,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$disturb,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$slash,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$fern,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$herb,useNA = "ifany")
table(plot_untidy$comm_stock, plot_untidy$inv_cov,useNA = "ifany")




```

```{r}

prop.table(table(plot_untidy$comm_stock, plot_untidy$mid_cov,useNA = "ifany"),margin=2)

prop.table(table(plot_untidy$comm_stock, plot_untidy$harvest, plot_untidy$location
                 ,useNA = "ifany"),margin=c(2,3))

#margin 2 is sum of second variable, and "3" is sum of third variable

```



###Frequency Table Plot Attributs_5
```{r}


freq_plot_attrib_5 <- plot_tidy %>% 
  filter(plot_attrib %in% c(
    "winner_stock", "comm_stock", "pre_comm_stock", "diver_stock",
    "pre_diver_stock", "interf_woody_stock","fern_stock", 
    "all_intr")
  ) %>% 
  group_by(harvest, location, plot_attrib, attrib_val) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n)) %>% 
  arrange(harvest, plot_attrib, location,  attrib_val)

write_csv(freq_plot_attrib_5, "freq_plot_attrib_5.csv")




```

###Frequency Table Plot Attributs_4
```{r}


freq_plot_attrib_4 <- plot_tidy %>% 
  mutate(harvest = fct_recode(harvest,
                              "sta_rd" = "boot",
                              "sta_rd" = "wedge")) %>% 
  filter(plot_attrib %in% c(
    "winner_stock", "comm_stock", "pre_comm_stock", "diver_stock",
    "pre_diver_stock", "interf_woody_stock","fern_stock", 
    "all_intr")
  ) %>% 
  group_by(harvest, location, plot_attrib, attrib_val) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n)) %>% 
  arrange(harvest, plot_attrib, location,  attrib_val)

write_csv(freq_plot_attrib_4, "freq_plot_attrib_4.csv")




```


