---
title: "Regneration Analysis"
author: "Peter Smallidge"
date: "10/17/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Analysis of regeneation plot data - 2019


```{r, include=FALSE}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
library(dplyr)
#
# ALT plus hypen = <- (within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# filter rows, select columns
# RMD comment = <!-- comment -->

```



### read data from csv file, check variables and data structure

<!-- note to self: in the "read_csv" code, after the file location the code
for 'col..." etc ensures that the specified column is adjusted to correct data type
the file "cheat sheet data-import" has details -->


```{r}
input.data = read_csv("~/R/slash-wall-vegetation/regen-data-2019.csv",
                      col_types=cols(spp=col_character(), sup.seed03=col_number(),
                                     sup.sapl=col_number()))
str(input.data)

regen.data <- input.data %>% 
  select(-other) %>%  # removes the column for "other"
  filter(!spp == "ush") %>%   #removes the row where species = "ush"
   # find a way to replace origin = u to origin 
  replace(is.na(.), 0) %>% 
  arrange(harvest, location, point, spp) %>% 
  print(n=15)

str(regen.data)

#check to ensure no unexpected values
  table(regen.data$spp)
  table(regen.data$origin)
  table(regen.data$radius.01)
  table(regen.data$radius.other)

#glimpse(regen.data)

skim(regen.data)
#str(regen.data)  there are xxxx rows in original data frame
head(regen.data)
#dim(regen.data)

```

### Convert plot seedling counts to per acre values by point

```{r}
# convert seedling counts to per acre values, data resolution for species by plot
# 1. convert missing (NA) to 0 else density values inflated (completed in previous chunk)
# 2. multiple *.seed01 x 1000 (radius 3.7 ft). use mutate
# 3. multiple *. x (radius = 6) use mutate
# 4. aggregate into "all suppressed" and "all exposed" and top4 per acre for each point
# 5. subsequently, need to average points for final values per acre

regen.per.acre <- regen.data %>% 
     mutate(
    sup.seed01A = sup.seed01 * (43560 /((3.14156) * (3.7 * 3.7))),
    sup.seed02A = sup.seed02 * (43560 /((3.14156) * (6 * 6))),
    sup.seed03A = sup.seed03 * (43560 /((3.14156) * (6 * 6))),
    sup.saplA = sup.sapl * (43560 /((3.14156) * (6 * 6))),
    exp.seed01A = exp.seed01 * (43560 /((3.14156) * (3.7 * 3.7))),
    exp.seed02A = exp.seed02 * (43560 /((3.14156) * (6 * 6))),
    exp.seed03A = exp.seed03 * (43560 /((3.14156) * (6 * 6))),
    exp.saplA = exp.sapl * (43560 /((3.14156) * (6 * 6)))
  ) %>% 
  mutate(
    suppressed = sup.seed01A + sup.seed02A + sup.seed03A + sup.saplA,
    exposed = exp.seed01A + exp.seed02A + exp.seed03A + exp.saplA,
    top4A = top4 * (43560 /((3.14156) * (6 * 6))) 
  ) %>% 
  select(harvest, location, point, spp, origin, sup.seed01A, sup.seed02A, sup.seed03A, sup.saplA,
         exp.seed01A, exp.seed02A, exp.seed03A, exp.saplA, suppressed, exposed, top4A)

regen.per.acre %>% 
  arrange(harvest, location, point, spp) %>% 
  print(n=25)

table(regen.per.acre$spp)
#view(regen.per.acre)
#write.table(regen.per.acre, "regen-acre-expanded.txt", sep="\t")

regen.per.acre %>% 
  write_csv(path = "\regen-acre-expanded.csv")

# commercial regeneration species
# 316 318 372 541 621 762  802 832 833 951 
# 
# desirable diversity species (no interfering, but includes Populus, paper birch, not pin cherry)
# 129 261 316 318 356 372 375 500 541 621 743 746 762 802 832 833  90 920 951
```

## DIVERSITY SPECIES
### calculate total seedling density for diversity species

```{r}
# Calculate total seedling desity of desirable non-interfering species
# 1. filter undesired or interfering species
# 2. 
diversity.per.acre_point <- regen.per.acre %>% 
  filter(spp %in% c("129", "261", "316", "318", "356", "372", "375", "500", "541", "621", "743",
                    "746", "762", "802", "832", "833", "90", "920", "951")) %>% 
  group_by(harvest, location, point) %>% 
  summarise(
    per.acre_point.supp = sum(suppressed), #need to total all species within a point
    per.acre_point.exp = sum(exposed),
    per.acre_point.top4 = sum(top4A)
  )
head(diversity.per.acre_point)

write.table(diversity.per.acre_point, "diversity-acre-point.txt", sep="\t")


diversity.per.acre <- diversity.per.acre_point %>% 
  group_by(harvest, location) %>% 
  summarize(
    per.acre.supp = mean(per.acre_point.supp),
    per.acre.exp = mean(per.acre_point.exp),
    per.acre.top4 = mean(per.acre_point.top4)
  )
head(diversity.per.acre)
write.table(diversity.per.acre, "diversity-acre.txt", sep="\t")


```


## COMMERCIAL SPECIES
### calculate total seedling density for commercial species

```{r}
# Calculate total seedling desity of desirable non-interfering species
# 1. filter undesired or interfering species
# 2. 

commercial.per.acre_point <- regen.per.acre %>% 
  filter(spp %in% c("316", "318",  "372", "541", "621",
                     "762", "802", "832", "833", "951")) %>% 
  group_by(harvest, location, point) %>% 
  summarise(
    per.acre_point.supp = sum(suppressed), #need to total all species within a point
    per.acre_point.exp01 = sum(exp.seed01A),
    per.acre_point.exp02 = sum(exp.seed02A),
    per.acre_point.exp03 = sum(exp.seed03A),
    per.acre_point.expsapl = sum(exp.saplA),
    per.acre_point.exp = sum(exposed),
    per.acre_point.top4 = sum(top4A)
  )
head(commercial.per.acre_point)

write.table(commercial.per.acre_point, "commercial-acre-point.txt", sep="\t")


commercial.per.acre <- commercial.per.acre_point %>% 
  group_by(harvest, location) %>% 
  summarize(
    per.acre.supp = mean(per.acre_point.supp),
    per.acre.exp01 = mean(per.acre_point.exp01),
    per.acre.exp02 = mean(per.acre_point.exp02),
    per.acre.exp03 = mean(per.acre_point.exp03),
    per.acre.expsapl = mean(per.acre_point.expsapl),
    per.acre.exp = mean(per.acre_point.exp),
    per.acre.top4 = mean(per.acre_point.top4)
  )
head(commercial.per.acre)
write.table(commercial.per.acre, "commercial-acre.txt", sep="\t")


```



