---
title: "Slash Wall Plot Analysis"
author: "Peter Smallidge"
date: "10/14/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
# Library: dplyr, expss, ggplot2, ggpubr, labeling, plyr,
#       tidyverse, skimr
library(tidyverse)
#library(plyr) # - conflicts with dplyr. If used, load dplyr after plyr
#library(dplyr)
#library(ggplot2)
#library(labeling)
#library(ggpubr)
#library(expss)
library(skimr)        ## install.packages("skimr")
#
# ALT plus hypen = <- (within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# filter rows, select columns
# 


```



<br>

## Read data files as csv located within the repository  
## Conduct basic visualization of the data  
## Use the function "skim" to provide summary statistics  

```{r}
#setwd("~/R/slash-wall-vegetation")
#input.data = read.table("plot-data-2019.csv", header = TRUE, sep = ",")
#plot.data <- input.data

plot.data = read_csv("~/R/slash-wall-vegetation/plot-data-2019.csv")


# str(input.data) displays the structure of the variables
skim(plot.data)
table(plot.data$ba)


### test the grouping function in skim, which reports "grouping" variables ###

plot.data %>% 
  arrange(harvest, location) %>% 
  group_by(harvest,location) %>% 
  skim()

head(plot.data, n=10)
tail(plot.data, n=10)

```

<br>

<!-- note to self: the following code was tried for purpose of manipulating data. Either it didn't work or was subsequently deemed not necessary -->


```{r}
#plot.data <- input.data
#code below to convert character variables to factor variables. I don't think this is necessary.
#
  #select(harvest, location, low.spp, invasive.spp, mid.spp, upper.spp, vine.spp) %>% 
 # mutate_if(is.character,as.factor)

#    These are redundant with the more thorough output of "skim"
#str(plot.data)
#glimpse(plot.data)
#names(plot.data)
#dim(plot.data)
#skimr::skim_tee(plot.data) - same as previous line

#the following does not work. Variable "maple" should be integer
#plot.data %>% 
#  mutate(vars(maple, na.rm=TRUE),integer)

#spec(plot.data)

#the following does not work...note maple is "character"
#plot.data %>% 
#  cols(
#    maple=col_integer()
#  )

```


<br>

### Subset data, group and summarize for harvest x location

```{r}
# Sort and group data by site (harvest name + interior vs. control)
# https://cmdlinetips.com/2020/08/dplyr-groupby-and-summarize-group-by-one-or-more-variables/ 
# Pat Sullivan suggested adding "as.data.frame()" which worked for him but not for me.
# Pat may have been using a different version of dyplr or maybe base R.
# Nina Thirkildsen suggested adding "dplyr::" before each verb. Including the package name
# is a way to ensure that it is the package's version of the verb that is used, 
# not a different package's verb.
# *** the problem was loading too many libraries with conflicts. Currently just load tidyverse and skimr


site <- plot.data %>% 
 #filter(location =="interior" | location=="control") %>% 
  select(harvest, location, ba) %>% 
  group_by(harvest, location) %>% 
  summarize(basal_area = mean(ba)) %>% 
  arrange(harvest, location)
  
site
write.table(site, "site_BA_means.txt", sep="\t")


```



```{r}

#write.table(site, "site_BA_means.txt", sep="\t")

```



```{r}
# site %>% 
# pivot_wider(names_from = location,
#             values_from = basal_area)
  
#view(ba_summ)

site %>% 
#  select(harvest, location, basal_area) %>% 
  table()



```

### Iteration of filter and select in attempt to de-bug ###
```{r}
site <- plot.data %>% 
  filter(location =="interior" | location=="control") %>% 
  select(harvest, location, ba)

  head(site)

```

<br>
### Iteration of filter, select and group_by


```{r}
site <- plot.data %>% 
  filter(location =="interior" | location=="control") %>% 
  select(harvest, location, ba) %>% 
  group_by(harvest, location)

head(site, n=10)
```

<br>
### Iteration of filter, select, group_by, and summarize

```{r}
site <- plot.data %>% 
  filter(location =="interior" | location=="control") %>% 
  select(harvest, location, ba) %>% 
  group_by(harvest, location) %>% 
  summarize(basal_area = mean(ba, na.rm = TRUE))

site

```

