---
title: "test of sample code"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
#library(dplyr)
#library(readr)

#
# ALT plus hypen = <- (must be within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# filter rows, select columns
# RMD comment = <!-- comment -->

```

### load data for sample coding

```{r}
test.df <- read_csv("commercial-per-acre-point.csv", 
    col_types = cols(point = col_integer())) %>% 
  select(harvest, location, point, comm.per.acre_point.exp01, count)

# ??
# where harvest == "crp" change to "rp"
# replace(test.df$harvest,)

  str(test.df)
  print(test.df, n=20)
  
```
### test code to replace values 

```{r}
library(tidyverse)
data <- tribble(
  ~X25, ~Other,
  "a", NA,
  "b", NA,
  "Other", "c",
  "Other", "d"
)
View(data)

data2 <- data %>% mutate(X25 = replace(X25, X25 == "Other", Other))
view(data2)

data3 <- data %>% 
  data$X25[data$X25 == a] <- "z"
view(data3)

num_vec <- c(1:4, NA)
num2 <- recode(num_vec, `2` = 20L, `4` = 40L)
view(num2)


# For factor values, use only named replacements
# and supply default with levels()
# code ....   factor_vec <- factor(c("a", "b", "c"))
# code ....   recode(factor_vec, a = "Apple", .default = levels(factor_vec))
#> [1] Apple b     c    
#> Levels: Apple b c


test <- tribble(
  ~plot, ~location, ~species,
  1, "p", 318,
  2, "p", 316,
  3, "i", 531,
  4, "i", 318
)
view(test)
str(test)

test2 <- test
test2$species[test2$species == 318] <-  "sm"
view(test2)



```



### calculate % of a variable within a group
### for each level of "harvest" what percentage are "interior" vs. "perimeter"

```{r}
# count the number of locations within each harvest
location.n <- test.df %>% 
  filter(location == "interior" | location == "perimeter")%>% 
  group_by(harvest, location) %>% 
  summarize(
    loc.numb = sum(count)
  )

head(location.n)

# count the number of harvests
harvest.n <- location.n %>% 
  group_by(harvest) %>% 
  summarize(
    harv.numb = sum(loc.numb)
  )

head(harvest.n)

#merge the counts by location with counts by harvest
loc.pct <- location.n %>% 
  full_join(harvest.n, by = "harvest") %>% 
  replace(is.na(.),0) %>% 
  mutate(
    location.pct = (loc.numb/harv.numb*100) # how to adjust significant digits?
  )

head(loc.pct)




 

```



### assign a value to a new variable based on the value of an existing variable
### stocking (seedlings per acre) should exceed 2887.5

```{r}

stocking.01 <- test.df %>% 
  rename(seedling.acre = comm.per.acre_point.exp01) %>% 
  str
  
plot_list <-  c(349, 350, 351)
 # unique(c(stocking.01$point))
 # c(349, 350, 351)
str(plot_list)

newdata = list()

for(pnt in plot_list){   # alternatively for(i in 1:20)
  stocking.02 <- stocking.01 %>% 
    filter(point == pnt) %>% 
    mutate(stk = 0) %>% 
    if (seedling.acre > 2887.5) { # do this with ifelse rather than the initial "stk=0"
      mutate(stk=1)
      
      newdata[[1]] <- stocking.02
    }
    }


```



### 