---
title: "veg_plot_graphs"
author: "Peter Smallidge"
date: "5/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Initialize Libraries
```{r, include=FALSE}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
library(readxl)
library(readr)
library(ggplot2) # - part of tidyverse
library(ggpubr)
#install.packages("viridis")
library(viridis)

#
# ALT plus hypen = <- (within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# ALT + - = insert assignment operator
# filter rows, select columns
# RMD comment = <!-- comment -->
# 
# 

#create folder to hold figures
dir.create("figures")

```


### Input Data Files
```{r}

stocking <- read_csv("freq_plot_attrib_4.csv")

```


```{r}
#column bar graph
#frequency plots stocked commercial
col01_slash <- stocking %>% 
  filter(attrib_val == "comm_stkd") %>% 
  ggplot((data=col01_slash),
    mapping = aes(x=harvest, y = freq, group = location))+
    geom_col(aes(x=harvest, y=freq, fill = location), position = "dodge")+
  theme_bw()+
  labs(
    x = "Harvest Site",
    y = "% of plots stocked with commercial tree species >4.5 ft",
    title = "Commercial Stocking after 3 Growing Seasons of Slash Wall",
    subtitle = "Arnot Forest, col01_slash, GH, veg_plot_graph"
  ) 


  
set_palette(col01_slash, palette = c(RdGy))  
#"uchicago"  ("#00AFBB", "#E7B800", "#FC4E07") ("#440154FF", "#21908CFF" , "#FDE725FF")

ggsave("figures/freq_plots_stocked_commercial.jpg")
  
  

```



```{r}


```

